### PR TITLE
remove Cargo.lock

### PR DESCRIPTION
**Pull request by astraw**
See https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

### CODE REVIEW

**Comment by jerry73204** [comment]
Added `Cargo.lock` to `.gitignore` and fixed a minor rustfmt warning.

**Comment by astraw** [comment]
Thanks. Actually I would be happy for a 0.1.3 release now. Would you if mind if my name was added to the author list in Cargo.toml? I can publish the release, or else I am happy if you do it.

**Comment by jerry73204** [comment]
Of course you can have your name there because you're already the maintainer.
The new release would hold a bit. I noticed the `build.rs` defaults to `pkg-config` and probes the apriltag library anyway. It would fail the build on docs.rs.

I'll look for a fix later (just finished a busy day), and we can release 0.1.3.

**Comment by astraw** [comment]
Good point about the build on docs.rs. I not in a big rush for a release, so I also prefer to do the best we can.

**Pull request merged**
